version: '3'
networks:
  app-tier:
    driver: bridge

services:
  database:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    networks:
      - "app-tier"
    volumes:
      - ./database:/var/lib/mysql

  backend:
    image: leorance/jisdac-node:v2.2
    networks:
      - "app-tier"
    environment:
      - APP_NAME=jisdacapp
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOSTNAME=database
      - DB_NAME=sample
      - DB_DIALECT=mysql
      - DB_PORT=3306
      - NODE_ENV=production
    depends_on:
      - database
    expose:
      - 3000

  frontend:
    image: leorance/jisdac-frontend:v1.3
    networks:
      - "app-tier"
    ports:
      - "80:3000"
    depends_on:
      - database
      - backend