version: '3'
networks:
  app-tier:
    driver: bridge

services:
  database:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    # expose:
    #   - 3306
    networks:
      - "app-tier"
    volumes:
      - ./database:/bitnami/mysql/data

  backend:
    image: leorance/jisdac-node:v1.1
    networks:
      - "app-tier"
    depends_on:
      - database
    ports:
      - "3000:3000"
    # expose:
    #   - 3000

  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - database
      - backend