server {
    listen 3000;
    server_name localhost;  # Or your server IP for now

    # Reverse proxy to Express
    location / {
        proxy_pass http://backend:3001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    access_log /var/log/nginx/express_access.log;
    error_log  /var/log/nginx/express_error.log;
}